# Site settings
title: Space Exploration Handbook
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/handbook" # the subpath of your site, e.g. /blog/
url: "http://launchacademy.com" # the base hostname & protocol for your site
twitter_username: LaunchAcademy_
github_username:  LaunchAcademy

# Outputting
permalink: none

# Build settings
markdown: kramdown

kramdown:
  input: GFM
